parameters:
  input_size: 40
  k: 3
  loss: hinge
  output_size: 1
  frac: 0.4
  samples: 1000
  


batch_size: 256
eval_batch_size: 1000
test_data_seed: 0
train_data_seed: 0

name : sparse_parity
unique_name: ${dataset.name}_n_${dataset.parameters.input_size}_k_${dataset.parameters.k}_train_${dataset.parameters.samples}_train_${dataset.parameters.frac}